# Insert chapter 2 title here

*Describe the work you have done this week and summarize your learning.*

- Describe your work and results clearly. 
- Assume the reader has an introductory course level understanding of writing and reading R code as well as statistical methods.
- Assume the reader has no previous knowledge of your data or the more advanced methods you are using.

```{r}
date()
```

Here we go again...
# Read the data into memory.Based on the students2014 data from my local folder,read the data into R
learning2014<-read.table("http://s3.amazonaws.com/assets.datacamp.com/production/course_2218/datasets/learning2014.txt", sep=",", header=TRUE)
learning2014
#Explore the structure of data
str(learning2014)
#Explore the dimension of data
dim(learning2014)
#From the data, we can see that there are 166 observations and 7 variables
# When we need to show a graphical overview of the data , we should access the GGally and ggplot2 libraries first.
library(GGally)
library(ggplot2)
# [-1] excludes the first column (gender)
pairs(learning2014[-1])
# create an plot matrix with ggpairs()
ggpairs(learning2014, lower = list(combo = wrap("facethist", bins = 20)))
# create a regression model with multiple explanatory variables
my_model <- lm(points ~ attitude + stra + surf+age+gender+deep, data = learning2014)

# print out a summary of the model
summary(my_model)
#The result shows that Attitude has the highest varible.
# create a regression model with three explanatory variables
my_model2 <- lm(points ~ attitude + stra + surf, data = learning2014)
# print out a summary of the model
summary(my_model2)
my_model2
# draw diagnostic plots using the plot() function. Choose the plots 1, 2 and 5
which<-c(1,2,5)
par(mfrow = c(2,2))
plot(my_model2,which)

#